#!/bin/sh
set -e

if ! getent group peat >/dev/null; then
    addgroup --system peat
fi
if ! getent passwd peat >/dev/null; then
    adduser --system --ingroup peat --home /var/lib/peat-node \
        --no-create-home --disabled-login --disabled-password peat
fi
install -d -o peat -g peat -m 0750 /var/lib/peat-node
chown -R -h peat:peat /var/lib/peat-node

config=/etc/peat-node/peat-node.env
config_template=/usr/share/peat-node/peat-node.env.example
if [ ! -s "$config" ]; then
    install -d -o root -g root -m 0755 /etc/peat-node
    install -o root -g peat -m 0640 "$config_template" "$config"
fi

#DEBHELPER#
