{{- if .Values.discovery.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "peat-node.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "peat-node.labels" . | nindent 4 }}
{{- end }}
