{{- if hasPrefix "tcp://" .Values.listen }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-peat-node
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "peat-node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: peat-node
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: grpc
      port: {{ (split ":" .Values.listen)._2 }}
      targetPort: grpc
      protocol: TCP
{{- end }}
